# Generated by Django 5.0.6 on 2024-07-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='temat',
            field=models.CharField(default='domyslna wartosc', max_length=500),
            preserve_default=False,
        ),
    ]
