# Generated by Django 5.0.6 on 2024-07-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_professionaluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('zakladanie_firmy', 'Zakładanie Firmy'), ('finance_inwestycje', 'Finanse i Inwestycje'), ('marketing_sprzedaz', 'Marketing i Sprzedaż'), ('zarządzanie_operacje', 'Zarządzanie i Operacje'), ('prawo_regulacje', 'Prawo i Regulacje'), ('rozwoj_osobisty', 'Rozwój Osobisty i Networking'), ('inne', 'Inne')], default='inne', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='is_professional',
            field=models.BooleanField(default=False),
        ),
    ]
