# Generated by Django 5.0.6 on 2024-07-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_comment_like_count_like_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='like_comment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
