# Generated by Django 5.0.6 on 2024-07-14 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_like_id_alter_like_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like_comment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='finance.comment'),
        ),
    ]
