# Generated by Django 5.0.6 on 2024-07-16 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_save'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_professional',
        ),
    ]
