# Generated by Django 5.0.6 on 2024-07-16 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_professionaluser_years_of_experience'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Save',
        ),
    ]
