# Generated by Django 5.0.6 on 2024-07-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_delete_save'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='if_professiona',
            field=models.BooleanField(default=False),
        ),
    ]
