# Generated by Django 5.0.6 on 2024-07-16 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_user_if_professiona'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='if_professiona',
            new_name='if_professional',
        ),
    ]
