# Generated by Django 5.0.6 on 2024-07-16 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_rename_if_professiona_user_if_professional'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professionaluser',
            old_name='avaliability',
            new_name='availability',
        ),
    ]
