# Generated by Django 5.0.6 on 2024-07-17 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_rename_avaliability_professionaluser_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Save_Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('if_save', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='save_post', to='finance.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='save_post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
