# Generated by Django 5.0.6 on 2024-07-20 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_save_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Rating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.PositiveSmallIntegerField()),
                ('if_used', models.BooleanField(default=False)),
                ('professional_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='finance.professionaluser')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
