# Generated by Django 5.0.6 on 2024-07-20 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_user_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_rating',
            old_name='rating',
            new_name='given_ratings',
        ),
        migrations.AlterField(
            model_name='user_rating',
            name='professional_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_rating', to='finance.professionaluser'),
        ),
    ]
