# Generated by Django 5.0.6 on 2024-07-20 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_rename_rating_user_rating_given_ratings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_rating',
            name='given_ratings',
        ),
        migrations.AddField(
            model_name='user_rating',
            name='reater',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
