# Generated by Django 5.0.6 on 2024-07-20 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_remove_user_rating_given_ratings_user_rating_reater'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_rating',
            old_name='reater',
            new_name='rater',
        ),
    ]
