# Generated by Django 5.0.6 on 2024-07-20 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_rename_reater_user_rating_rater'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating_User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.PositiveSmallIntegerField()),
                ('if_used', models.BooleanField(default=False)),
                ('professional_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='give_rate_professional', to='finance.professionaluser')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='give_rate_professional', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User_Rating',
        ),
    ]
