# Generated by Django 5.0.6 on 2024-07-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_rating_user_delete_user_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating_user',
            name='opinion',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
