# Generated by Django 5.0.6 on 2024-09-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0026_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('zakladanie_firmy', 'Zakładanie firmy'), ('finance_inwestycje', 'Finanse i inwestycje'), ('marketing_sprzedaz', 'Marketing i sprzedaż'), ('zarządzanie_operacje', 'Zarządzanie i operacje'), ('prawo_regulacje', 'Prawo i regulacje'), ('rozwoj_osobisty', 'Rozwój osobisty i networking'), ('inne', 'Inne')], default='inne', max_length=50),
        ),
    ]
